apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
spec:
  selector:
    app: pod-haproxy
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
    - name: admin-port
      protocol: TCP
      port: 8404
      targetPort: 8404
  type: NodePort
